// Datos base de Rienda migrados desde el Excel. Se cargan una sola vez.

export const SEED = `
INSERT INTO perfil (id, nombre) VALUES (1, 'Julian');

-- Categorias (se eligen al cargar un gasto)
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Transporte');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Otros');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Salidas');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Ropa');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Comidas');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Facturas');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Compras');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Regalos');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Educación / Salud');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Inversión');
INSERT INTO categoria (perfil_id, nombre) VALUES (1, 'Viaje');

-- Subcategorias (derivadas del detalle)
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Auto');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Hogar');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Otra Salida');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Ropa');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Boliche');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Pedidos');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Bar');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Aplicaciones');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Supermercado');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Carnicería');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Alquiler');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Trabajo');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Sube');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Postre');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Mio');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Banco');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Asado');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Regalos Gen.');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Farmacia');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Mercado');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Joda');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Kiosco');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Peluquería');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Deportes');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Psicologa');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Internet');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Yerba');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Donación');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Previa');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'ABL');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Edenor');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Expensas');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Puestito');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Comida');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Casa');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Verdulería');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Restaurante');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Ahorro');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Cafetería');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Gasto Viaje');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Abru');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Cotillón');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Documentación');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Rappifavor');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Suplementos');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Curso');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Pan');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Dolares');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Correo');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Recuerdo');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Bici');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Osde');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Calzoncillos');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'REGALADO');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Avellaneda');
INSERT INTO subcategoria (perfil_id, nombre) VALUES (1, 'Guitarra');

-- Mapeo detalle -> subcategoria (resuelve el id por nombre)
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Auto', id FROM subcategoria WHERE perfil_id=1 AND nombre='Auto';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Hogar', id FROM subcategoria WHERE perfil_id=1 AND nombre='Hogar';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Bowling', id FROM subcategoria WHERE perfil_id=1 AND nombre='Otra Salida';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Pantalón', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ropa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Boliche', id FROM subcategoria WHERE perfil_id=1 AND nombre='Boliche';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Pizza', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Bar', id FROM subcategoria WHERE perfil_id=1 AND nombre='Bar';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Aplicaciones', id FROM subcategoria WHERE perfil_id=1 AND nombre='Aplicaciones';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Supermercado', id FROM subcategoria WHERE perfil_id=1 AND nombre='Supermercado';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Carnicería', id FROM subcategoria WHERE perfil_id=1 AND nombre='Carnicería';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Alquiler', id FROM subcategoria WHERE perfil_id=1 AND nombre='Alquiler';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Hamburguesa', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Trabajo', id FROM subcategoria WHERE perfil_id=1 AND nombre='Trabajo';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Sube', id FROM subcategoria WHERE perfil_id=1 AND nombre='Sube';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Parrilla', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Postre', id FROM subcategoria WHERE perfil_id=1 AND nombre='Postre';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Mio', id FROM subcategoria WHERE perfil_id=1 AND nombre='Mio';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Banco', id FROM subcategoria WHERE perfil_id=1 AND nombre='Banco';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Asado', id FROM subcategoria WHERE perfil_id=1 AND nombre='Asado';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Empanadas', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Shawarma', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Amigos', id FROM subcategoria WHERE perfil_id=1 AND nombre='Regalos Gen.';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Farmacia', id FROM subcategoria WHERE perfil_id=1 AND nombre='Farmacia';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Compañero trabajo', id FROM subcategoria WHERE perfil_id=1 AND nombre='Regalos Gen.';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Mercado', id FROM subcategoria WHERE perfil_id=1 AND nombre='Mercado';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Joda', id FROM subcategoria WHERE perfil_id=1 AND nombre='Joda';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Kiosco', id FROM subcategoria WHERE perfil_id=1 AND nombre='Kiosco';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Familia', id FROM subcategoria WHERE perfil_id=1 AND nombre='Regalos Gen.';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Panadería', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Peluquería', id FROM subcategoria WHERE perfil_id=1 AND nombre='Peluquería';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Gimnasio', id FROM subcategoria WHERE perfil_id=1 AND nombre='Deportes';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Psicologa', id FROM subcategoria WHERE perfil_id=1 AND nombre='Psicologa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Internet', id FROM subcategoria WHERE perfil_id=1 AND nombre='Internet';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Yerba', id FROM subcategoria WHERE perfil_id=1 AND nombre='Yerba';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Alegría intensiva', id FROM subcategoria WHERE perfil_id=1 AND nombre='Donación';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Cine', id FROM subcategoria WHERE perfil_id=1 AND nombre='Otra Salida';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Evento', id FROM subcategoria WHERE perfil_id=1 AND nombre='Otra Salida';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Previa', id FROM subcategoria WHERE perfil_id=1 AND nombre='Previa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Abl Lmc', id FROM subcategoria WHERE perfil_id=1 AND nombre='ABL';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Abl Aguero', id FROM subcategoria WHERE perfil_id=1 AND nombre='ABL';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Edenor', id FROM subcategoria WHERE perfil_id=1 AND nombre='Edenor';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Expensas', id FROM subcategoria WHERE perfil_id=1 AND nombre='Expensas';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Futbol', id FROM subcategoria WHERE perfil_id=1 AND nombre='Deportes';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Puestito', id FROM subcategoria WHERE perfil_id=1 AND nombre='Puestito';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Comida', id FROM subcategoria WHERE perfil_id=1 AND nombre='Comida';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Casa', id FROM subcategoria WHERE perfil_id=1 AND nombre='Casa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Verdulería', id FROM subcategoria WHERE perfil_id=1 AND nombre='Verdulería';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Restaurante', id FROM subcategoria WHERE perfil_id=1 AND nombre='Restaurante';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Ahorro', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ahorro';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Sushi', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Tequeños', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Paddle', id FROM subcategoria WHERE perfil_id=1 AND nombre='Deportes';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Cafetería', id FROM subcategoria WHERE perfil_id=1 AND nombre='Cafetería';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Rotisería', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Brasil', id FROM subcategoria WHERE perfil_id=1 AND nombre='Gasto Viaje';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Pasta', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Abru', id FROM subcategoria WHERE perfil_id=1 AND nombre='Abru';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Mar del plata', id FROM subcategoria WHERE perfil_id=1 AND nombre='Gasto Viaje';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Cataratas', id FROM subcategoria WHERE perfil_id=1 AND nombre='Gasto Viaje';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Cotillón', id FROM subcategoria WHERE perfil_id=1 AND nombre='Cotillón';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Comodoro', id FROM subcategoria WHERE perfil_id=1 AND nombre='Gasto Viaje';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Mar del Plata', id FROM subcategoria WHERE perfil_id=1 AND nombre='Gasto Viaje';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Documentación', id FROM subcategoria WHERE perfil_id=1 AND nombre='Documentación';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Accesorios', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ropa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Remera', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ropa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Compra donación', id FROM subcategoria WHERE perfil_id=1 AND nombre='Donación';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Rappifavor', id FROM subcategoria WHERE perfil_id=1 AND nombre='Rappifavor';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Escalada', id FROM subcategoria WHERE perfil_id=1 AND nombre='Deportes';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Camisa', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ropa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Medias', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ropa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Abrigo', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ropa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Calzado', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ropa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Suplementos', id FROM subcategoria WHERE perfil_id=1 AND nombre='Suplementos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Curso', id FROM subcategoria WHERE perfil_id=1 AND nombre='Curso';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Silvio', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ropa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Pan', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pan';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Teatro', id FROM subcategoria WHERE perfil_id=1 AND nombre='Otra Salida';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Dolares', id FROM subcategoria WHERE perfil_id=1 AND nombre='Dolares';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Arreglo', id FROM subcategoria WHERE perfil_id=1 AND nombre='Ropa';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Arepa', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Trevelin', id FROM subcategoria WHERE perfil_id=1 AND nombre='Gasto Viaje';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Correo', id FROM subcategoria WHERE perfil_id=1 AND nombre='Correo';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Combustible', id FROM subcategoria WHERE perfil_id=1 AND nombre='Auto';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Ushuaia', id FROM subcategoria WHERE perfil_id=1 AND nombre='Gasto Viaje';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Recuerdo', id FROM subcategoria WHERE perfil_id=1 AND nombre='Recuerdo';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Campo', id FROM subcategoria WHERE perfil_id=1 AND nombre='Gasto Viaje';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Bici', id FROM subcategoria WHERE perfil_id=1 AND nombre='Bici';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Osde', id FROM subcategoria WHERE perfil_id=1 AND nombre='Osde';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Locro', id FROM subcategoria WHERE perfil_id=1 AND nombre='Pedidos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Calzoncillos', id FROM subcategoria WHERE perfil_id=1 AND nombre='Calzoncillos';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Carnet', id FROM subcategoria WHERE perfil_id=1 AND nombre='Documentación';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'REGALADO', id FROM subcategoria WHERE perfil_id=1 AND nombre='REGALADO';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Avellaneda', id FROM subcategoria WHERE perfil_id=1 AND nombre='Avellaneda';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Córdoba', id FROM subcategoria WHERE perfil_id=1 AND nombre='Gasto Viaje';
INSERT INTO mapeo_detalle (perfil_id, detalle, subcategoria_id) SELECT 1, 'Guitarra', id FROM subcategoria WHERE perfil_id=1 AND nombre='Guitarra';

-- Tarjetas
INSERT INTO tarjeta (perfil_id, nombre, proveedor, tipo) VALUES (1, 'Santander Visa', 'Visa', 'credito');
INSERT INTO tarjeta (perfil_id, nombre, proveedor, tipo) VALUES (1, 'Santander American Express', 'Amex', 'credito');
INSERT INTO tarjeta (perfil_id, nombre, proveedor, tipo) VALUES (1, 'Mercado Pago', 'Mastercard', 'credito');
INSERT INTO tarjeta (perfil_id, nombre, proveedor, tipo) VALUES (1, 'Cocos', 'Mastercard', 'credito');
INSERT INTO tarjeta (perfil_id, nombre, proveedor, tipo) VALUES (1, 'Mercado Pago Débito', 'Mastercard', 'debito');
INSERT INTO tarjeta (perfil_id, nombre, proveedor, tipo) VALUES (1, 'Santander Débito', 'Visa', 'debito');
`;